- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Check if Homebrew is installed
      block:
        - name: Check if Homebrew is installed
          homebrew:
            update_homebrew: true
          check_mode: true
        - name: Homebrew available
          debug:
            msg: Homebrew is installed
      rescue:
        - name: No homebrew
          debug:
            msg: Homebrew is not installed

  tasks:
    - name: Install ssh keys
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml

    - name: Setup terminal and shell
      ansible.builtin.import_tasks:
        file: tasks/terminal.yml

    - name: Setup tmux
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml

