- hosts: localhost
  connection: local
  gather_facts: true
  pre_tasks:
    - name: Check if running on macOS
      ansible.builtin.fail:
        msg: "This playbook only runs on macOS. Detected OS: {{ ansible_os_family }}"
      when: ansible_os_family != "Darwin"

    - name: Check if Homebrew is installed
      block:
        - name: Check if Homebrew is installed
          homebrew:
            update_homebrew: true
          check_mode: true
        - name: Homebrew available
          debug:
            msg: Homebrew is installed
      rescue:
        - name: No homebrew
          debug:
            msg: Homebrew is not installed

  tasks:
    - name: Install ssh keys
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml

    - name: Setup terminal and shell
      ansible.builtin.import_tasks:
        file: tasks/terminal.yml

    - name: Setup git
      ansible.builtin.import_tasks:
        file: tasks/git.yml

    - name: Setup yabai and skhd
      ansible.builtin.import_tasks:
        file: tasks/yabai.yml

    - name: Setup nvm and Node.js
      ansible.builtin.import_tasks:
        file: tasks/nvm.yml

    - name: Setup pyenv and Python
      ansible.builtin.import_tasks:
        file: tasks/python.yml

    - name: Setup Go
      ansible.builtin.import_tasks:
        file: tasks/go.yml

    - name: Setup Ruby
      ansible.builtin.import_tasks:
        file: tasks/ruby.yml

    - name: Setup neovim
      ansible.builtin.import_tasks:
        file: tasks/neovim.yml

    - name: Setup Docker
      ansible.builtin.import_tasks:
        file: tasks/docker.yml

    - name: Setup dev tools
      ansible.builtin.import_tasks:
        file: tasks/devtools.yml

    - name: Install apps
      ansible.builtin.import_tasks:
        file: tasks/apps.yml

