- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Check if Homebrew is installed
      block:
        - name: Check if Homebrew is installed
          homebrew:
            update_homebrew: true
          check_mode: true
        - name: Homebrew available
          debug:
            msg: Homebrew is installed
      rescue:
        - name: No homebrew
          debug:
            msg: Homebrew is not installed

  tasks:
    - name: Install ssh keys
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml

    - name: Setup terminal and shell
      ansible.builtin.import_tasks:
        file: tasks/terminal.yml

    - name: Setup tmux
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml

    - name: Setup git
      ansible.builtin.import_tasks:
        file: tasks/git.yml

    - name: Setup yabai and skhd
      ansible.builtin.import_tasks:
        file: tasks/yabai.yml

    - name: Setup nvm and Node.js
      ansible.builtin.import_tasks:
        file: tasks/nvm.yml

    - name: Setup pyenv and Python
      ansible.builtin.import_tasks:
        file: tasks/python.yml

    - name: Setup Go
      ansible.builtin.import_tasks:
        file: tasks/go.yml

    - name: Setup Ruby
      ansible.builtin.import_tasks:
        file: tasks/ruby.yml

    - name: Setup neovim
      ansible.builtin.import_tasks:
        file: tasks/neovim.yml

