- name: Install GoLand
  community.general.homebrew_cask:
    name: goland
    state: present

- name: Install DataGrip
  community.general.homebrew_cask:
    name: datagrip
    state: present

- name: Install Google Chrome
  community.general.homebrew_cask:
    name: google-chrome
    state: present

- name: Install Claude desktop
  community.general.homebrew_cask:
    name: claude
    state: present

- name: Install Anki
  community.general.homebrew_cask:
    name: anki
    state: present

- name: Install Telegram
  community.general.homebrew_cask:
    name: telegram
    state: present

- name: Install VLC
  community.general.homebrew_cask:
    name: vlc
    state: present

- name: Install Tailscale
  community.general.homebrew_cask:
    name: tailscale
    state: present
