- name: Install CLI tools
  community.general.homebrew:
    name:
      - awscli
      - jq
      - bat
      - tree
      - vim
      - argocd
      - nmap
      - semgrep
      - pipx
      - virtualenv
      - stow
    state: present
