- name: Install Claude Code
  community.general.homebrew_cask:
    name: claude-code
    state: present

- name: Install Terraform
  community.general.homebrew:
    name: terraform
    state: present


- name: Install Google Cloud SDK
  community.general.homebrew_cask:
    name: google-cloud-sdk
    state: present
