- name: Ensure .config/tmux directory exists
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux"
    mode: '0755'
    state: directory

- name: Copy tmux.conf
  ansible.builtin.copy:
    src: "../files/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/tmux.conf"
    mode: '0644'
